### ISSUE TITLE
'attempt to subtract with overflow' panic on invalid expression

### ISSUE THREAD

**Issue by badboy** [mitsuhiko/minijinja#49]
## Description

The following code panics:

```rust
use minijinja::Environment;

fn main() {
    let env = Environment::new();
    let expr = env.compile_expression("\\{").unwrap();
}
```

with:

```
thread 'main' panicked at 'attempt to subtract with overflow', minijinja/src/error.rs:282:23
```

Relevant part of the stacktrace:

```
  16:        0x10306a21c - minijinja::error::debug_info::render_debug_info::hcd5508172021c006
                               at /Users/jer/code/rust/minijinja/minijinja/src/error.rs:282:23
  17:        0x10305a028 - <minijinja::error::Error as core::fmt::Debug>::fmt::h8cd2dc17739d34ea
                               at /Users/jer/code/rust/minijinja/minijinja/src/error.rs:53:17
```

If no expression name is given, it uses `<expression>` and sets a lineno.
[That happens in `parse_expr`](https://github.com/mitsuhiko/minijinja/blob/1c61aa8354ea6e4eba723b5c432e4dd46a005d8b/minijinja/src/parser.rs#L866). 
However `current_span().start_line` is `0` there, leading to the undeflow later.

## Reproduction steps

1. Compile and run the code
2. Observe the panic

## What did you expect

It shouldn't panic, but fail to parse the expression.

**Comment by badboy** [comment]
Note: if the `debug` feature is disabled obviously the undeflowing code path is not triggered and the code above panics on the unwrap with:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: SyntaxError, detail: Some("unexpected character"), name: Some("<expression>"), lineno: 0, source: None }', examples/expr/src/main.rs:5:46
```
